# Generated by Django 6.0.6 on 2026-07-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='preferred_hospitals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='premium_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
