# Generated by Django 6.0.6 on 2026-07-07 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0004_customer_preferred_hospitals_customer_premium_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_band', models.CharField(choices=[('Low', 'Low Risk'), ('Moderate', 'Moderate Risk'), ('High', 'High Risk')], max_length=20)),
                ('confidence', models.FloatField()),
                ('insights', models.JSONField()),
                ('triggered_rules', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_insights', to='advisors.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
