# Generated by Django 6.0.6 on 2026-07-12 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0006_aioutputversion_airequestlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='airequestlog',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='airequestlog',
            old_name='prompt',
            new_name='prompt_text',
        ),
        migrations.RemoveField(
            model_name='airequestlog',
            name='response',
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='log_type',
            field=models.CharField(choices=[('chat', 'Chat'), ('question_suggestion', 'Question Suggestion'), ('qualification_insight', 'Qualification Insight')], default='chat', max_length=50),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='response_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='tokens_used',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='advisors.customer'),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='model_name',
            field=models.CharField(default='gemini-flash-latest', max_length=100),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='status',
            field=models.CharField(default='success', max_length=20),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AIOutputVersion',
        ),
    ]
