# Generated by Django 6.0.6 on 2026-07-13 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0007_rename_timestamp_airequestlog_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIOutputVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_type', models.CharField(choices=[('question_suggestion', 'Question Suggestion'), ('missing_info', 'Missing Information'), ('qualification', 'Qualification Insights'), ('chat', 'AI Chat')], max_length=50)),
                ('version_number', models.IntegerField(default=1)),
                ('response_json', models.JSONField()),
                ('model_used', models.CharField(default='gemini-pro', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_output_versions', to='advisors.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'output_type', 'version_number')},
            },
        ),
    ]
