# Generated by Django 6.0.6 on 2026-07-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0008_aioutputversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airequestlog',
            name='log_type',
            field=models.CharField(choices=[('chat', 'Chat'), ('question_suggestion', 'Question Suggestion'), ('qualification_insight', 'Qualification Insight')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
