# Generated by Django 6.0.6 on 2026-08-12 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0009_alter_airequestlog_log_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='existinginsurancecover',
            name='policy_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('policy_type', models.CharField(choices=[('Life', 'Life Insurance'), ('Health', 'Health Insurance'), ('Auto', 'Auto Insurance'), ('Home', 'Home Insurance'), ('Travel', 'Travel Insurance'), ('Other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('term_years', models.IntegerField(default=20)),
                ('proposal_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Quoted', 'Quoted'), ('Proposed', 'Proposed'), ('Active', 'Active'), ('Lapsed', 'Lapsed'), ('Declined', 'Declined')], default='Draft', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_policies', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='advisors.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', '-created_at'], name='advisors_po_agent_i_1029d3_idx'), models.Index(fields=['customer', '-created_at'], name='advisors_po_custome_a7a3db_idx'), models.Index(fields=['status'], name='advisors_po_status_93f641_idx')],
            },
        ),
    ]
